version: 2

formats: all

conda:
    environment: environment.yml

build:
    image: latest
python:
  version: 3.6
  install:
    - method: setuptools
    - path: .
    - requirements: requirements_dev.txt
  system_packages: True
